code --install-extension EditorConfig.EditorConfig
code --install-extension GabrielBB.vscode-lombok
code --install-extension Pivotal.vscode-boot-dev-pack
code --install-extension alexdima.copy-relative-path
code --install-extension bierner.markdown-preview-github-styles
code --install-extension dbaeumer.vscode-eslint
code --install-extension DotJoshJohnson.xml
code --install-extension dzannotti.vscode-babel-coloring
code --install-extension felixfbecker.php-intellisense
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension marcostazi.VS-code-vagrantfile
code --install-extension mikestead.dotenv
code --install-extension mrmlnc.vscode-apache
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension naco-siren.gradle-language
code --install-extension Pivotal.vscode-concourse
code --install-extension Pivotal.vscode-manifest-yaml
code --install-extension Pivotal.vscode-spring-boot
code --install-extension redhat.java
code --install-extension robertohuertasm.vscode-icons
code --install-extension steve8708.Align
code --install-extension vscjava.vscode-spring-initializr
code --install-extension xabikos.JavaScriptSnippets
code --install-extension xabikos.ReactSnippets
code --install-extension zhuangtongfa.Material-theme
